version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://your-ec2-public-ip:8080 # For Local use this : http://localhost:8080 
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./leave-management
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"  # Add backend port mapping
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - db
    networks:
      - app-network


  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    networks:
      - app-network

volumes:
  pgdata:  # Persists PostgreSQL data on EC2’s disk

networks:
  app-network:  # Private network for inter-container communication
