version: '3.8'

services:
  frontend:
    build: ./frontend  # Path to frontend Dockerfile
    ports:
      - "80:3000"      # Map EC2 port 80 → container port 3000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend   # Path to backend Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=secret
    networks:
      - app-network

  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    networks:
      - app-network

volumes:
  pgdata:  # Persists PostgreSQL data on EC2’s disk

networks:
  app-network:  # Private network for inter-container communication
